### PR TITLE
basic html file

### PR DESCRIPTION
**Pull request by UofTL**
Hey,

Here the basic html. Please review and approve.
If approve please move issue #1  to done.
thanks,
L

### CODE REVIEW

**Review by nerink — CHANGES_REQUESTED** [review]
in the HTML page, change "!" to 1

**Comment by UofTL** [comment]
As per request, changed as been completed, please review and approve.

thanks,

L

**Review by nerink — APPROVED** [review]
approved changes

**Review by SiyanGuo — APPROVED** [review]
good to go

**Pull request merged**
